name = Terramaster Simple
description = A simple 3 column layout mobile first and Susy.
preview = preview.png
template = terramaster-simple-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[bottom-left]  = Bottom left
regions[bottom-center]  = Bottom center
regions[bottom-right] = Bottom right
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/simple/simple.layout.css
